/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Counter: typeof import('./../src/components/Counter.vue')['default']
    IMaterialSymbolsLanguage: typeof import('~icons/material-symbols/language')['default']
    IMdiCardAccountDetails: typeof import('~icons/mdi/card-account-details')['default']
    IMdiHome: typeof import('~icons/mdi/home')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
